# 应用名称
spring:
  application:
    name: cloud-dubbo-provider
  cloud:
    nacos:
      discovery:
        server-addr: 60.205.230.70:8848
server:
  port: 8888
application:
  base-package: com.js
dubbo:
  scan:
    base-packages: ${application.base-package}.service
  protocol:
    port: 20880
    name: dubbo
    id: cloud-dubbo-proivider
#  registry:
#    address: nacos://60.205.230.70:8848


