# 应用名称
spring:
  application:
    name: cloud-dubbo-provider
  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8888
application:
  base-package: com.js



