# 应用名称
spring:
  application:
    name: dubbo-provider
server:
  port: 8080

dubbo:
  scan:
    base-packages: com.js.service
#  protocol:
#    port: -1
#    name: dubbo
#    id: dubbo-proivider
  application:
    name: dubbo-provider # dubbo应用名
    register-mode: instance # 服务注册模式：dubbo3.0新增配置
