# 应用名称
spring:
  application:
    name: dubbo-provider
server:
  port: 8080

dubbo:
  application:
    qos-port: 33333
    qos-enable: true
  scan:
    base-packages: com.js.service
  protocol:
    port: -1
    name: dubbo
    id: dubbo-proivider
