# 应用名称
spring:
  application:
    name: cloud-dubbo-consumer
  cloud:
    compatibility-verifier:
      enabled: false
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8889
application:
  base-package: com.js

dubbo:
  application:
    service-discovery:
      migration: FORCE_APPLICATION  # dubbo3.0新增配置