# 应用名称
spring:
  application:
    name: cloud-dubbo-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 60.205.230.70:8848
server:
  port: 8889
application:
  base-package: com.js
dubbo:
  cloud:
    # 表示要订阅服务的服务名，可以配置'*'，
    # 代表订阅所有服务，不推荐使用。若需订阅多应用，使用 "," 分割
    subscribed-services: cloud-dubbo-provider
  protocol:
    port: -1
    name: dubbo
#  registry:
#    address: nacos://60.205.230.70:8848


