# 应用名称
spring:
  application:
    name: dubbo-consumer
server:
  port: 8081

dubbo:
  registry:
    use-as-config-center: false
  application:
    service-discovery:
      migration: FORCE_APPLICATION  # dubbo3.0新增配置
  scan:
    base-packages: com.js.service

logging:
  config: classpath:logback/logback-spring.xml
